linters:
  enable:
    - errcheck
    - staticcheck
    - unused
    - govet
    - ineffassign
    - gofmt
    - goimports
    - gosimple
    - misspell

issues:
  exclude-rules:
    # Exclude errcheck in test files - common practice
    - path: _test\.go
      linters:
        - errcheck
    # Exclude unused in test files - test helpers are often unused
    - path: _test\.go
      linters:
        - unused
