version: "2"

linters:
  default: none
  enable:
    - errcheck
    - staticcheck
    - unused
    - govet
    - ineffassign
    - misspell
  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - path: _test\.go
        linters:
          - unused

formatters:
  enable:
    - gofmt
    - goimports
