version: 2

project_name: codely

before:
  hooks:
    - go mod tidy

builds:
  - id: codely
    binary: codely
    main: ./cmd/codely
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/charliek/codely/internal/cli.Version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: charliek
    name: codely
  draft: false
  prerelease: auto
  mode: replace

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
